data:
  input_column_classes: '[2.0, 3.0, 4.0, 4.0, 2.0, 2.0, 5.0]'
  input_num_size: 12
  num_outputs: 1

model:
  name: 'Tabtransformer'
  embed_size: 32
  identifier_ratio: 8
  aggregate_method: 'concat'
  depth: 6
  num_heads: 8
  dropout_rate: 0.01
  mlp_unit_ratios: '[4, 2]'
  inference_activation: 'sigmoid'

train:
  epochs: 50
  batch_size: 32
  buffer_size: 100
  learning_rate: 0.01
  early_stopping: True
  stop_patience: 30
#  loss_fn: tfa.losses.SigmoidFocalCrossEntropy
  loss_fn: losses.BinaryCrossentropy
  optimize_fn: optimizers.Adam
  loss_metric: metrics.BinaryCrossentropy
  evaluate_metric: metrics.BinaryAccuracy

random:
  random_seed: 'None'

mlflow:
  experiment_name: 'TabTransformer-Titanic'
